export enum COURSE_ACTIONS {
  ADD_COURSE = 'ADD_COURSE',
  LOAD_COURSES = 'LOAD_COURSES',
  STORE_COURSES = 'STORE_COURSES',
  UPDATE_COURSE = 'UPDATE_COURSE',
  DELETE_COURSE = 'DELETE_COURSE',
  ERROR_LOAD = 'ERROR_LOAD'
}
