export enum COURSE_ACTIONS {
  ADD_COURSE = 'ADD_COURSE',
  LOAD_COURSES = 'LOAD_COURSES',
  STORE_COURSES = 'STORE_COURSES',
  UPDATE_COURSE = 'UPDATE_COURSE',
  DELETE_COURSE = 'DELETE_COURSE',
  ERROR_LOAD = 'ERROR_LOAD'
}

export enum AUTH_ACTIONS {
  AUTH = 'AUTH',
  LOGIN = "LOGIN",
  LOGIN_FAILED = "LOG_FAILED",
}